#!/usr/bin/env bash
#
# Bootstrap the Habrok Python environment for Theisus retrieval pipeline.
# Idempotent — safe to re-run. Prints what it's doing; exits on any error.
#
# Run from project root on the Habrok login node:
#   bash scripts/habrok/setup_env.sh
#
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"
echo "[setup] project root: $ROOT_DIR"

# ----- 1. Modules ----------------------------------------------------------
# Adjust these to whatever Habrok currently provides. `module avail` lists
# what's installed. Common module names below; verify with `module spider`.
echo "[setup] loading modules…"
module purge
module load Python/3.11.5-GCCcore-13.2.0    # adjust if a 3.11.x is named differently
module load CUDA/12.4.0                     # match torch's CUDA build
module load OpenSSL/1.1                     # often needed for httpx / hf hub

echo "[setup] python = $(python --version)"
echo "[setup] cuda   = $(nvcc --version | tail -n1 || echo 'nvcc not on PATH')"

# ----- 2. Virtualenv -------------------------------------------------------
VENV="$ROOT_DIR/.venv-habrok"
if [ ! -d "$VENV" ]; then
    echo "[setup] creating venv at $VENV"
    python -m venv "$VENV"
fi
# shellcheck disable=SC1091
source "$VENV/bin/activate"
python -m pip install --upgrade pip wheel

# ----- 3. Install pinned deps ---------------------------------------------
# Install the HABROK inference deps (requirements-habrok.txt), NOT the local
# requirements.txt — the latter is the scraping/prototyping set (playwright,
# spacy, openai) and lacks torch/transformers, so the OLMo job would die on
# `import torch`. Fall back to a minimal inline set only if the file is absent.
HABROK_REQS="$ROOT_DIR/requirements-habrok.txt"
if [ -f "$HABROK_REQS" ]; then
    echo "[setup] installing from requirements-habrok.txt"
    pip install -r "$HABROK_REQS"
else
    echo "[setup] requirements-habrok.txt missing — installing minimal set"
    pip install \
        "torch==2.5.1" \
        "transformers>=5.0" \
        "accelerate>=1.0" \
        "bitsandbytes>=0.43" \
        "sentence-transformers>=3.0" \
        "qdrant-client>=1.10" \
        "rank-bm25>=0.2.2" \
        "langdetect>=1.0.9" \
        "numpy" "tqdm"
fi

# ----- 4. HuggingFace cache → /scratch ------------------------------------
# Models are 10s-100s of GB. $HOME quotas are small on Habrok. Redirect HF
# downloads to scratch and persist the env var for future shells / jobs.
SCRATCH_HF="/scratch/$USER/hf-cache"
mkdir -p "$SCRATCH_HF"
ENV_FILE="$ROOT_DIR/scripts/habrok/env.sh"
cat > "$ENV_FILE" <<EOF
# Auto-generated by setup_env.sh — source me before any python job
export HF_HOME=$SCRATCH_HF
export HF_HUB_DOWNLOAD_TIMEOUT=120
export TOKENIZERS_PARALLELISM=false
EOF
echo "[setup] wrote $ENV_FILE  (HF_HOME → $SCRATCH_HF)"

# ----- 5. Sanity check ----------------------------------------------------
echo "[setup] verifying CUDA-visible torch"
python - <<'PY'
import torch
print(f"  torch={torch.__version__}  cuda_available={torch.cuda.is_available()}  "
      f"device_count={torch.cuda.device_count()}")
if torch.cuda.is_available():
    print(f"  device 0 = {torch.cuda.get_device_name(0)}")
PY

echo
echo "[setup] done."
echo "Next:  source scripts/habrok/env.sh   (or your job script will do it)"
echo "       sbatch scripts/habrok/generate_questions.slurm"
