"""
End-to-end attribution on ONE (or a few) question(s) — the RQ3 2×2 in miniature.

For each question it runs both attribution lenses on the SAME OLMo answer and
crosses them:

                       in training data? (OLMoTrace, extrinsic)
                         yes                    no
  context-     high   corpus-grounded use   context-driven, novel
  driven?      ───────────────────────────────────────────────
  (MIRAGE,     low    parametric recall     UNVERIFIED  ← hallucination signal
  intrinsic)

This is the thesis-ceiling experiment at n=1: pick a `rescued` question (dense
never retrieved the gold passage, hybrid+rerank did), give the model that
context, and ask — did it *causally use* the retrieved passage (CTI), and is the
content traceable to OLMo's training data (OLMoTrace)?

Staged for a 16 GB GPU: the retriever is loaded and freed BEFORE the OLMo
attributor loads, so they're never resident together. OLMoTrace is an HTTP call
(no GPU). Prototype on the 4080 with the 7B; scale on Habrok with --model 32B.

Usage
-----
    # one rescued contrast question, default 7B
    .venv311/Scripts/python.exe -m attribution.run_attribution \\
        --questions data/attribution_smoke.txt --limit 1

    # skip the live OLMoTrace call (intrinsic only; fully offline)
    .venv311/Scripts/python.exe -m attribution.run_attribution \\
        --questions data/attribution_smoke.txt --limit 1 --no-olmotrace
"""

import argparse
import gc
import json
import sys
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent.parent / "data"


def free_gpu():
    gc.collect()
    try:
        import torch
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
    except Exception:
        pass


def load_questions(path: Path) -> list[str]:
    return [ln.strip() for ln in path.read_text(encoding="utf-8").splitlines()
            if ln.strip() and not ln.strip().startswith("#")]


def quadrant(reliance: str, parametric) -> str:
    """The 2×2 cell label for a span."""
    ctx = reliance == "context"
    if parametric is None:
        return "context-use (trace n/a)" if ctx else "parametric? (trace n/a)"
    if ctx and parametric:
        return "corpus-grounded use"
    if ctx and not parametric:
        return "context-driven, novel"
    if not ctx and parametric:
        return "parametric recall"
    return "UNVERIFIED (hallucination signal)"


def main() -> int:
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass
    ap = argparse.ArgumentParser(description=__doc__.strip().split("\n")[0])
    ap.add_argument("--questions", default=str(DATA_DIR / "attribution_smoke.txt"))
    ap.add_argument("--limit", type=int, default=1)
    ap.add_argument("--model", default="allenai/Olmo-3-7B-Instruct")
    ap.add_argument("--dtype", choices=["auto", "fp16", "bf16"], default="bf16")
    ap.add_argument("--collection", default="theisus_none")
    ap.add_argument("--bm25-path", default=str(DATA_DIR / "bm25_index.pkl"))
    ap.add_argument("--qdrant-path", default=str(DATA_DIR / "qdrant"))
    ap.add_argument("--top-k", type=int, default=6, help="passages of context")
    ap.add_argument("--max-new-tokens", type=int, default=200)
    ap.add_argument("--no-olmotrace", action="store_true",
                    help="skip the live OLMoTrace call (intrinsic only)")
    ap.add_argument("--olmotrace-model-id", default="Olmo-3.1-32B-Instruct",
                    help="index to trace against (the answer here is generated by "
                         "--model; for final numbers keep generator and index aligned)")
    ap.add_argument("--out-dir", default=str(DATA_DIR / "attribution"))
    args = ap.parse_args()

    questions = load_questions(Path(args.questions))[: args.limit]
    if not questions:
        print("No questions loaded.", file=sys.stderr)
        return 2
    print(f"{len(questions)} question(s); model={args.model}\n")

    # ---- Stage 1: retrieve (load + free before OLMo) ----
    from attribution.pipeline import Retriever
    print("Stage 1/3 — retrieval (hybrid + rerank)")
    retriever = Retriever(qdrant_path=args.qdrant_path, collection=args.collection,
                          bm25_path=args.bm25_path, use_hybrid=True, use_rerank=True)
    passages_by_q = [retriever.retrieve(q, top_k=args.top_k) for q in questions]
    retriever.close()
    del retriever
    free_gpu()

    # ---- Stage 2: intrinsic attribution (MIRAGE owns generation) ----
    from attribution.mirage import MirageAttributor
    print("Stage 2/3 — MIRAGE intrinsic attribution (generate + CTI + CCI)")
    mirage = MirageAttributor(model=args.model, dtype=args.dtype)
    results = [mirage.attribute(q, ps, max_new_tokens=args.max_new_tokens)
               for q, ps in zip(questions, passages_by_q)]
    del mirage
    free_gpu()

    # ---- Stage 3: extrinsic provenance (OLMoTrace, HTTP) + report ----
    print("Stage 3/3 — OLMoTrace extrinsic provenance\n")
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    traces = {}
    if not args.no_olmotrace:
        from attribution.pipeline import olmotrace_answer
        for r in results:
            ok, tr = olmotrace_answer(r.question, r.answer, pretraining_only=True,
                                      max_documents=10)
            traces[r.question] = (ok, tr)

    from attribution.pipeline import span_training_matches

    for r in results:
        print("=" * 78)
        print(f"Q: {r.question}")
        ctx_tags = ", ".join(f"{t}={v['title']}" for t, v in list(r.passage_tags.items())[:3])
        print(f"context (top passages): {ctx_tags}")
        print(f"\nANSWER:\n{r.answer}\n")
        ok, tr = traces.get(r.question, (False, {}))
        print(f"{'span (sentence)':<52} {'CTI':>6} {'reliance':<11} {'src':<4} 2×2 cell")
        print("-" * 78)
        record_spans = []
        for s in r.spans:
            matches = span_training_matches(s.text, tr) if ok else []
            parametric = bool(matches) if ok else None
            cell = quadrant(s.reliance, parametric)
            short = (s.text[:48] + "…") if len(s.text) > 49 else s.text
            print(f"{short:<52} {s.cti_mean:6.2f} {s.reliance:<11} "
                  f"{s.top_passage or '-':<4} {cell}")
            record_spans.append({
                "text": s.text, "cti_mean": round(s.cti_mean, 4), "cti_max": round(s.cti_max, 4),
                "reliance": s.reliance, "top_passage": s.top_passage,
                "passage_saliency": s.passage_saliency,
                "parametric": parametric, "training_matches": matches,
                "quadrant": cell,
            })
        # persist for inspection
        rec = {
            "question": r.question, "model": args.model, "answer": r.answer,
            "olmotrace_ok": ok, "olmotrace_model_id": args.olmotrace_model_id,
            "passage_tags": r.passage_tags, "spans": record_spans,
        }
        fid = "".join(c if c.isalnum() else "-" for c in r.question.lower())[:50]
        (out_dir / f"attrib-{fid}.json").write_text(
            json.dumps(rec, ensure_ascii=False, indent=2), encoding="utf-8")
        print()
    print(f"Wrote {len(results)} record(s) to {out_dir}")
    print("\nNote: CTI threshold (context vs parametric) is set in attribution/mirage.py "
          "(CTI_STRONG/CTI_WEAK) — calibrate on a labelled handful before trusting buckets.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
